### Numpy learning from various tutorials

First tutorial: http://cs231n.github.io/python-numpy-tutorial/#numpy

1. Array Creation

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [3]:
b = np.zeros((3,4,5))
print(b)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [5]:
c = np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
d = np.full((2,2), 3)
print(d)

[[3 3]
 [3 3]]


In [8]:
e = np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
f= np.random.rand(3)
print(f)

[0.21019164 0.90557905 0.71941015]


2. Array Indexing

In [13]:
np.random.seed(19)
arr = np.random.rand(3,3)
print(arr)

[[0.0975336  0.76124972 0.24693797]
 [0.13813169 0.33144656 0.08299957]
 [0.67197708 0.8065938  0.98274191]]


In [14]:
print(arr[:2])

[[0.0975336  0.76124972 0.24693797]
 [0.13813169 0.33144656 0.08299957]]


In [15]:
print(arr[:2,:1])

[[0.0975336 ]
 [0.13813169]]


Skipping integer array indexing from the tutorial.
The basic idea from indexing is:
1. we can get single elements
2. we can get sub-arrays
    - through slicing
    - through integer arrays

Skipping arithmetic from the tutuorial

Skipping broadcasting too for now - will do it later in this tutuorial

In [19]:
i = np.random.random((3,1))
print(i.shape)
print(i)

(3, 1)
[[0.38700677]
 [0.68832738]
 [0.37292716]]


In [23]:
z = np.array([2,3]).reshape(2,1)
z

array([[2],
       [3]])

In [24]:
x = np.array([5,6]).reshape(2,1)
x

array([[5],
       [6]])

In [29]:
np.dot(x.T,z).shape

(1, 1)